### PR TITLE
Add armv6 support

### PR DESCRIPTION
**Pull request by ghost**
Use CXX instead of LD. LD will cause problem on armv6 anytime soon.
Use SNAP_ARCH instead of if/elif/else...

### CODE REVIEW

**Comment by ghost** [comment]
I don't have an i386 machine, can you check if make -V Makefile works as expected on an i386 arch?

**Comment by vgrebenschikov** [comment]
% uname -m
i386
% make -V MAKEFILE
i386_bsd.mk
%  make -V Makefile

%

Builds ok on i386.

**Comment by vgrebenschikov** [comment]
Thanks!

**Comment by vgrebenschikov** [comment]
@MikaelUrankar hm, arm_v6_bsd.mk does not exists in snap7 distribution, 
I've added

**Pull request merged**
